VERSION 0.6
FROM registry.jetbrains.team/p/writerside/builder/writerside-builder:232.10165.1

docs_build:
  COPY docs docs
  ENV DISPLAY :99
  RUN Xvfb :99 & /opt/builder/bin/idea.sh helpbuilderinspect -source-dir=docs -product docs/typed-fastify -output-dir artifacts

docs_test:

