on:
  push:
    branches:
      - main
name: main
jobs:
  test:
    environment: main
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 21, 22, 24]
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
      - run: node --version
      - run: pnpm install
      - run: pnpm test
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      - run: pnpm build
