on:
  pull_request:
name: PR
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [20, 21, 22]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
      - run: node --version
      - run: pnpm install
      - run: pnpm test
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      - run: pnpm build
