# https://github.com/GoogleCloudPlatform/release-please-action
on:
  push:
    branches:
      - main
name: release-please
permissions:
  contents: write
  pull-requests: write
jobs:
  release-please-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: release-pr
        uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: '@coobaha/typed-fastify'
          command: release-pr
          prerelease: true
  release-please-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: '@coobaha/typed-fastify'
          command: github-release
          prerelease: true
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - id: build
        if: ${{ steps.release.outputs.release_created }}
        run: |
          pnpm install
          pnpm build
          pnpm test
      - id: publish
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: pnpm publish --access public
