# https://github.com/GoogleCloudPlatform/release-please-action
on:
  push:
    branches:
      - main
      - next
name: release-please
jobs:
  release-please-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - id: release-pr
        uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: '@coobaha/typed-fastify'
          command: release-pr
  release-please-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: '@coobaha/typed-fastify'
          command: github-release
      # The logic below handles the npm publication:
        # these if statements ensure that a publication only occurs when
        # a new release is created:
      - uses: actions/setup-node@v3
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
      - id: build
        if: ${{ steps.release.outputs.release_created }}
        run: |
          yarn install
          yarn build
          yarn test
      - id: publish
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: yarn npm publish --access public
